# Generated by Django 5.1.5 on 2025-02-20 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='entrer votre prenom', max_length=20)),
                ('last_name', models.CharField(help_text='entrer votre nom', max_length=20)),
                ('email', models.CharField(help_text='entrer votre email', max_length=100)),
                ('number', models.CharField(help_text='entrer votre numero de telephone', max_length=10)),
                ('user', models.OneToOneField(blank=True, help_text='Link to the Django user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
