# Generated by Django 5.1.5 on 2025-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contenance',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='disponibility',
            field=models.CharField(blank=True, choices=[('en stock', 'En Stock'), ('rupture de stock', 'Rupture De Stock')], help_text='la disponibilité de produit', max_length=30, null=True),
        ),
    ]
