# Generated by Django 5.1.5 on 2025-02-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_contenance_product_disponibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contenance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
