# Generated by Django 5.1.5 on 2025-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_contenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contenance',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
