# Generated by Django 5.1.5 on 2025-02-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_order_product_order_quantity_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contenance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
