# Generated by Django 5.1.5 on 2025-02-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_contenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('en cours de traitement', 'En cours de traitement'), ('expédié', 'Expédié'), ('livrè', 'Livré'), ('annulé', 'Annulé')], default='pending', max_length=40),
        ),
    ]
