# Generated by Django 4.2.19 on 2025-02-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_remove_order_client_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multi_function_variants',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
