# Generated by Django 4.2.19 on 2025-02-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_variant_remove_product_multi_function_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productvariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productvariant'),
        ),
    ]
