# Generated by Django 4.2.19 on 2025-02-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_order_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantchoice',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productvariant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='VariantChoice',
        ),
    ]
