# Generated by Django 4.2.19 on 2025-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
