# Generated by Django 4.2.19 on 2025-02-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_order_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
