# Generated by Django 4.2.19 on 2025-06-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_order_p_variant_alter_order_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
    ]
