# Generated by Django 4.2.19 on 2025-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_order_payment_date_order_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
