# Generated by Django 4.2.19 on 2025-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(default='votre adresse ?', help_text='entrer votre BUSINESS Adresse', max_length=100),
        ),
    ]
