# Generated by Django 4.2.19 on 2025-07-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_shippingcost_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingcost',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
