# Generated by Django 4.2.19 on 2025-07-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_alter_commune_wilaya_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='contenance',
        ),
        migrations.AlterField(
            model_name='product',
            name='disponibility',
            field=models.CharField(blank=True, choices=[('en stock', 'En Stock'), ('rupture de stock', 'Rupture De Stock')], help_text='La disponibilité du produit', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_types', to='ecommerce.mainvariant')),
            ],
        ),
        migrations.AddField(
            model_name='mainvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_variants', to='ecommerce.product'),
        ),
    ]
