# Generated by Django 4.2.19 on 2025-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_mainvariant_remove_product_contenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitytype',
            name='quantity_per_type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
