# Generated by Django 4.2.19 on 2025-07-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_quantitytype_quantity_per_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contenance',
        ),
        migrations.AddField(
            model_name='order',
            name='main_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.mainvariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.quantitytype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='p_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productvariant'),
        ),
    ]
