# Generated by Django 4.2.19 on 2025-07-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_remove_order_contenance_order_main_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantitytype',
            name='quantity_per_type',
        ),
    ]
