# Generated by Django 4.2.19 on 2025-07-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_remove_quantitytype_quantity_per_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
