# Generated by Django 4.2.19 on 2025-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_order_unit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainvariant',
            name='m_display_name',
            field=models.CharField(default='p', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='o_display_name',
            field=models.CharField(default='p', max_length=100),
            preserve_default=False,
        ),
    ]
