# Generated by Django 4.2.19 on 2025-07-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_mainvariant_m_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainvariant',
            name='m_display_name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='o_display_name',
        ),
    ]
