# Generated by Django 4.2.19 on 2025-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_remove_mainvariant_m_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='udf1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
