# Generated by Django 4.2.19 on 2025-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_order_udf1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('en attente', 'En Attente'), ('avec succés', 'Avec Succés'), ('echoué', 'Echoué'), ('annuler', 'Annuler')], default='pending', max_length=20),
        ),
    ]
